### ISSUE TITLE
Whitelist fails CORS when not browsing using IP address

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#184] opened 2016-11-02 20:45 UTC
@JunaidZA commented on [Mon Jul 11 2016](https://github.com/pi-hole/pi-hole/issues/565)

##### Expected Behaviour:

Adding a domain to whitelist 
##### Actual Behaviour:

Does not add to whitelist as the JavaScript call fails CORS
##### Steps to reproduce this issue:

Browse the pihole admin using the PM's domain name, not it's IP and add try to add a domain to the whitelist
##

---

@Mcat12 commented on [Mon Jul 11 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-231715543)

I'll link to a Reddit post with a similar question (are you the same person?) http://www.reddit.com/r/pihole/comments/4sa7hh/_/ Though we should have put the hostname of the Pi-hole in the accepted origins.

---

@Windyo commented on [Sun Jul 31 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236457268)

To add to this issue :
For those of use who have a multi-purpose Pi, the same problem arises if we decide to use another port for the WebAdmin.
For example, I have my pi-hole webadmin set up on port 8017 ; whitelisting fails CORS because of that.
Going to pi.hole redirects to what I have hosted on port 80, which is expected but not volontary behavior.

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236464979)

[This](https://github.com/pi-hole/pi-hole/issues/546#issuecomment-235917230) will help for having a different port.

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236582061)

@Mcat12 followed the steps, still fails CORS for some reason.

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236583793)

Did you modify the change for your custom port? And are you going to the page using `http://pi.hole:8017/admin/`?

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236585314)

I modified `/var/www/html/admin/php/sub.php` and `/var/www/html/admin/php/sub.php`
to 
```
// Check CORS
if($_SERVER['HTTP_ORIGIN'] == "http://pi.hole:8017" || $_SERVER['HTTP_ORIGIN'] == "http://${_SERVER['SERVER_ADDR']}:8017")
    header("Access-Control-Allow-Origin: ${_SERVER['HTTP_ORIGIN']}");
else if($_SERVER['HTTP_HOST'] == $_SERVER['SERVER_ADDR'] || $_SERVER['HTTP_HOST'] == "pi.hole")
    header("Access-Control-Allow-Origin: ${_SERVER['HTTP_HOST']}");
else
    die("Failed CORS");`
```
and tried accessing the panel via `http://my.ad.dr.es.ss:8017/admin` and `http://pi.hole:8017/admin`, no dice.

Edit (Mcat12): Reformatted code block. ;)

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236586721)

~~Ah, I forgot to mention one thing. Those `header(...)` lines need to also have the port on them.~~
nvm, they should work...

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236607203)

Are you using Internet Explorer or Edge?

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236608038)

Where should I put the port in the Header lines ?
I am using firefox and Chrome  interchangeably

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236609957)

That comment was actually wrong, since `$_SERVER['HTTP_ORIGIN']` should contain the port. Add this line right after `// Check CORS`:
```
echo $_SERVER['HTTP_ORIGIN'];
```
And then follow [these](https://github.com/pi-hole/pi-hole/issues/546#issuecomment-233498279) instructions (using your correct port of course).

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236626375)

I failed to get it working following the instructions.
I ended up bypassing CORS for now.

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236627038)

What was in the response? Remember that by removing CORS, you are removing a security feature.

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236627615)

The response was still "failed CORS" with no other information, even after adding `echo $_SERVER['HTTP_ORIGIN'];`.

I'm not psyched about removing CORS but if I don't my less technically-inclined co-users of the router can't bypass the pihole when need be, which is a much bigger problem in my book. 

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236627780)

Did you add that `echo` line to `add.php` as well as `sub.php`?

---

@Windyo commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236629420)

Yes.

---

@Mcat12 commented on [Mon Aug 01 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-236629932)

Weird... afaik Chrome sends the Origin header along with all requests, including same-origin ones... Well, in the dev version of the web interface, we are handling CORS better, so this would not be an issue if the Origin header is missing.

---

@xac1d commented on [Wed Oct 19 2016](https://github.com/pi-hole/pi-hole/issues/565#issuecomment-254707428)

i had the same issue. maybe this can help you https://www.reddit.com/r/pihole/comments/52icnm/nginx_reverse_proxy_not_working_with_pihole/

**Comment by Mcat12** [comment] 2016-11-08 00:46
Closing issue for now, as we have been unable to prove that the issue is caused by Pi-hole itself.

**Closed by Mcat12** 2016-11-08 00:46 UTC
