### ISSUE TITLE
There is an update available overlays home page

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#121] opened 2016-08-05 15:48 UTC
@vinceskahan commented on [Fri Aug 05 2016](https://github.com/pi-hole/pi-hole/issues/610)

With 2.8.0 installed, I'm nagged mercilessly to update by an overlay on your home screen which pops annoyingly over far too much of the screen.

Please change where your update available info appears, a small 'update available' thing to the left of the pihole logo would be plenty sufficient for notifying us, the massive rectangular popup is a bit much.
##

**Comment by DL6ER** [comment] 2016-11-21 14:26
I cannot reproduce this, but I think it may have already been fixed. I close this issue clearing up our issues page.

@vinceskahan Feel free to reopen this issue if the problem is still there for you (with the current release).

This is how it looks if updates are available for me:
![screenshot at 2016-11-21 15-21-57](https://cloud.githubusercontent.com/assets/16748619/20486044/7e2b6b68-affe-11e6-8f5e-41cd2f1b78d0.png)

![screenshot at 2016-11-21 15-22-05](https://cloud.githubusercontent.com/assets/16748619/20486051/83e258dc-affe-11e6-878a-41a63fb117e2.png)

**Closed by DL6ER** 2016-11-21 14:26 UTC

**Comment by PromoFaux** [comment] 2016-11-21 14:43
Ah yeah, this was fixed a while back!
