### ISSUE TITLE
Group same clients with multiple IPs in Client group management

### ISSUE THREAD

**Issue by Ullmie02** [pi-hole/AdminLTE#1273] opened 2020-05-12 16:38 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

If I want to add a client to the configured clients list, it would be very practical to group all IPs (especially IPv6) of this one client (determined by MAC-Address/Hostname) in the list into one entry. I think this should technically be possible, as in the Network tab, all the IPs of one client get grouped into one entry like this:
![network overview](https://user-images.githubusercontent.com/16425113/81720406-a7c95080-947e-11ea-843a-ca8d6a708e71.png)

**Actual behaviour:**

Each IPv4 and IPv6 of the clients is shown as a separate entry in the dropdown. Currently, to add one client you have to add every IP as a configured client and add each to the group individually. In my current setup, one physical device shows up in the dropdown as up to 10 different entries with separate IPs:
![client group management](https://user-images.githubusercontent.com/16425113/81721024-8026b800-947f-11ea-8e4c-d7aa5da04ebf.png)

**Steps to reproduce:**

Network where clients make DNS requests over IPv4 and IPv6

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

hx9bxuffla

**Troubleshooting undertaken, and/or other relevant information:**

None

**Comment by DL6ER** [comment] 2020-05-12 17:38
We're currently discussing in various places how to improve on the client selection. The issue is that when we change the philosophy from `per IP address` to `per device`, we can only do this properly for immediate neighbors of your Pi-hole. Everything connected through a VPN, separated by a VLAN, etc. cannot be determined using this method.

We would, however, loose the ability to define entire ranges clients in subnets, like `192.168.1.0/24`.

Discussions are ongoing but. In order to ensure there aren't too many places where this is happening, I'm closing this issue ticket. Rest assured that we're working on improvements and they'll likely come at some point (maybe not v5.1, but not that far away, either).

**Closed** 2020-05-12 17:40 UTC
