### ISSUE TITLE
Enable/Disable button refresh issue

### ISSUE THREAD

**Issue by chtaylo2** [pi-hole/AdminLTE#882] opened 2018-12-27 20:20 UTC
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?: 1

**Expected behaviour:**

In the Admin UI, when clicking Enable / Disable + timeframe, the service should react accordingly. For example, if I select 5 minutes to disable, then change to "Permanently", it should process this.

**Actual behaviour:**

In the Admin UI, if you click "Disable" + select any timeframe (ie.: 5 minutes), before the time expires, select "Permanently", it keeps the countdown going and re-enables at 00:00. If you refresh the browser page prior to reaching 00:00, the Permanent disable setting is retained. This is seen on the most current version:

-   Current Pi-hole version is v4.1.1
-   Current AdminLTE version is v4.1.1
-   Current FTL version is v4.1.2

**Steps to reproduce:**

See steps above on how to re-produce. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A - Have re-produced this on multiple devices.

**Troubleshooting undertaken, and/or other relevant information:**

Tried this on multiple Pi's to confirm it's not just me. Looks to be a bug.

Thanks!

**Comment by Mcat12** [comment] 2018-12-28 15:04
It's not intended to allow you to disable twice before re-enabling, so the bug seems to be that this is allowed.

**Comment by DL6ER** [comment] 2018-12-29 13:03
I just tried this. When I click `Disable -> For 30 seconds`, the menu disappears and only a count down for enabling appears:

![screenshot from 2018-12-29 14-01-54](https://user-images.githubusercontent.com/16748619/50538622-5b73be00-0b72-11e9-98bc-43d1769bfc2b.png)

This also stays when reloading the page. I don't see how one should be able to select another disabling interval as the menu should be hidden after the first selection.

**Comment by chtaylo2** [comment] 2018-12-29 17:02
Here's a screen recording of what I'm referring to. When it's **Enabled (0:00:XX)** and you click the button, it disables as you'd expect. But if you then select "Permanently", it doesn't honor that selection. It's not a major issue, just a bug I noticed.

![pi-hole-disable](https://user-images.githubusercontent.com/16865602/50540525-45a9cd00-0b61-11e9-9958-9796d5c73710.gif)

**Comment by DL6ER** [comment] 2018-12-29 17:49
Ah, thank you very much for the short movie, we will work on this.

**Comment by nicedevil007** [comment] 2019-10-02 11:31
I can confirm that on my devices in a bit more strange behaviour.
I'm using Pihole and its WebGui for administration on the one hand and on the other the given API to be used with node-red (node from @naimo84). 

Sometimes (not always) I hit my 15 Min disable timer over the api and then I take a look @ the webgui => any other time is shown there... not just a few seconds off, sometime 5-8 Minutes!
If I enable it on the webgui and then turn it off there for 900 sec (15 min) it is working as intended.

Pihole is running in a Docker-Contaier with the offical image pihole/pihole:latest in my installation.

Maybe this helps any dev to get a deeper look into this bug?

**Comment by DL6ER** [comment] 2019-10-02 16:24
@Mcat12 @PromoFaux I seem to remember that we talked about this and we might actually have fixed this but there is no pull request referencing this issue ticket - do you know more?

**Comment by Mcat12** [comment] 2019-10-09 18:42
I also don't see any PR fixing this. It seems like more of a UI issue than an issue with the enable/disable mechanic, which means it shouldn't be too hard to fix.

**Comment by rdwebdesign** [comment] 2022-01-29 04:19
The button behavior has changed.
The period selection CAN NO LONGER BE CHANGED during the countdown.

The current behavior is:
- you select any period (even Permanently);
- the button shows the text "Enable" + countdown;
- if you click the button again, it will be re-enabled immediately.

I will close the issue. If necessary, it can be reopened.

**Closed by rdwebdesign** 2022-01-29 04:19 UTC
Labels: Bug
