### ISSUE TITLE
Web admin page mishandles custom date ranges. It has an off-by-24-hours error on the ending timestamp.

### ISSUE THREAD

**Issue by jeffstearns** [pi-hole/AdminLTE#897] opened 2019-01-19 03:10 UTC
Expected behaviour:

The "Long term data -> Query Log" screen displays today's data when today's date is entered as a one-day custom range.

Actual behaviour:

`The "Long term data -> Query Log" page  displays no data when the default date range is used.

Specifically, today's date/time is January 18th 2019, 19:00.  The "Date and time range" thus defaults to
"January 18th 2019, 00:00 - January 18th 2019, 23:59".  Although the Pi-hole has been operating all day, this query shows no data.

The problem is not limited to today's date. It actually affects any date.

The bug appears to be an off-by-one error in the code that handles _custom date ranges_. The code seems to subtract 24 hours from the end-of-range timestamp.

Steps to reproduce:

Install Pi-hole on a fresh machine.
Let it run for a minutes.

Confirm that data is present:
Open the Pi-hole Admin Console in Chrome or similar browser.
Navigate to Long term data -> Query Log.
Click in the "Date and time range" panel.
Press the "Today" button.
Today's data appears as expected. This confirms that data is present.

Observe the bug:
Click in the "Date and time range" panel.
Press the "Custom Range" button.
Select today as the starting and ending date. (In my case, that date is January 18th 2019.)
Press "Apply".
Note that the date range is truly a 24-hour period. In my case, it is displayed as "January 18th 2019, 00:00 - January 18th 2019, 23:59".
Note that no data is displayed. The screen says "No data available in table". This is wrong.

Debug token provided by uploading pihole -d log:   e2oggegc2g

Troubleshooting undertaken, and/or other relevant information:
This is repeatable.
The bug applies to all 3 submenu items under the "Long term data" menu.
The bug seems to be that the code isn't properly parsing the timestamp for the end-of-range.

I am running Pi-hole version 4.1.1.  This bug is not new; I first noticed it in August 2018.

**Comment by DL6ER** [comment] 2019-01-19 09:08
I cannot reproduce this. However, I'm seeing a different error see my description below.

> `The "Long term data -> Query Log" page displays no data when the default date range is used.

The default range is suggested as `January 19th 2019, 00:00 - January 19th 2019, 23:59` in my case. This is correct, as:
```
$ LC_TIME="en_US.UTF8" date
Sat Jan 19 10:03:13 CET 2019
``

With this, I obtain the following output:
![screenshot from 2019-01-19 10-01-26](https://user-images.githubusercontent.com/16748619/51424702-c47aae80-1bd1-11e9-976a-d48ea5c4f00a.png)

This is not what I requested as it shows also *some* data from yesterday (from 20:50 to 23:59) although I have not requested them. I will check this today as report back.

Meanwhile, please ensure that the time zones on both your client (where you access the web interface from) and on the Pi-hole are configured correctly just to ensure that the bugs we see aren't the same and in your case it's just a miss-configured timezone that comes on top.

**Comment by DL6ER** [comment] 2019-01-20 11:03
@jeffstearns I added some improvements to the long-term statistics page, however, I am still unable to reproduce the issue you are seeing.

Please check your time zones as detailed in my previous post.

**Comment by jeffstearns** [comment] 2019-01-21 01:42
@DL6ER; sorry, I'm not sure how to find the "previous post" you refer to.   I read #898 but that doesn't mention any timezones.  Thus I don't know which time zones you're referring to.

Nonetheless, I'll try to give some info that might be helpful.

I am in the US/Pacific timezone (the offset is UTC -7).  My local machine is a Mac; it is set to "US/Pacific" and has a long history of handling timestamps properly.  The Pi-hole server is in the same room with me.  The date and time are set correctly on the Pi-hole host.  The `date` command produces the expected output.  It agrees with the Mac. 

Using the web interface, I can browse to various Pi-hole admin pages and see timestamps.  They are correct in all cases I observe.

- Dashboard
- Query Log
- Tools->"Tail pihole.log"

I  surveyed the timestamps on log entries at /var/log/pihole*; they look correctly localized in all cases.

Hope this helps.  If you could point out some configuration values I should check, I'd be happy to do that.  Thanks!

**Comment by dschaper** [comment] 2019-01-21 02:16
Which browser does this show the wrong dates with?

**Comment by jeffstearns** [comment] 2019-01-21 07:56
@dschaper I typically use Chrome on OS X.

But note that this bug (#897) doesn't involve the browser showing wrong dates.  Maybe you're thinking about a different bug?

**Comment by DL6ER** [comment] 2019-01-21 16:47
> I'm not sure how to find the "previous post" you refer to.

Last paragraph [here](https://github.com/pi-hole/AdminLTE/issues/897#issuecomment-455762796), but you already answered my question.

> doesn't involve the browser showing wrong dates

Oh, it does (somehow)! The dates you select (both start and end datetime) get converted to UTC *by your browser* before they are sent to the Pi-hole API which processes the data. Please open Chrome's developer tools (typically they are connected to [F12]) and go to the Network tab. Then select "Today" and click "Apply". A new item will be added on this list. Please copy the full URL and post it here.

Hint: It should look like http://pi.hole/admin/api_db.php?getGraphData&from=1548025200&until=1548089178.789 just with different numbers.

**Comment by jeffstearns** [comment] 2019-01-21 19:14
@DL6ER Thanks for the helpful suggestions.

I did some tests with the **Long term data** pages.  There's an interesting piece of information here:
**Long term data->Query log**, with date range chosen via **Today** button:
	The browser loads **http://10.5.4.2/admin/api_db.php?getAllQueries&from=1548057600&until=1548096361.495&_=1548096361212**
	The browser displays a list with today's data.

**Long term data->Graphics**, with the default data & time range:
	The Data and time range is listed as “January 21st 2019, 00:00 - January 21st, 2019 23:59"
	<the browser loads some .js and fonts, but _does not make a call to api_db.php_>
	The browser draws a chart labeled “Queries over the selected time period”.  The chart contains no data.

**Long term data->Graphics**, with date range chosen via **Today** button:
	The browser loads **http://10.5.4.2/admin/api_db.php?getGraphData&from=1548057600&until=1548096547.57**

**Long term data->Graphics**, with date range "January 21 2019, 00:00 - January 22 2019, 00:00"chosen via **Custom Range** button:
	The browser loads **http://10.5.4.2/admin/api_db.php?getGraphData&from=1548057600&until=1548096547.57**

So there's a bug wherein the browser doesn't call api_db.php when the default date and time range is used.  This bug could explain the problem described in the first 6 paragraphs of this bug report.

**Comment by DL6ER** [comment] 2019-01-21 19:20
Thanks, the bug with the **initially set** (I guess this is what you mean by "default") custom range not being handled correctly is known and fixed by #899 

> So there's a bug wherein the browser doesn't call api_db.php when the default date and time range is used.

On all long-term data pages the expected behavior is to only load data only you clicked the `Apply` button. The tables/graphs are and stay initially empty. Do you think it would be more meaningful if we'd leave the field empty at first until the user clicked on something like `Today`?

**Comment by jeffstearns** [comment] 2019-01-21 19:41
I open a web browser and navigate to Long term data->Graphics.

	The browser displays a chart labeled Compute graphical statistics from the Pi-hole query database
	The date and time range correctly lists today’s date.
	The chart is empty.
	There is no Apply button.  There are no buttons at all.

What I expect is to see today’s data in the chart.  So I think the most meaningful thing is to display the data that corresponds with the chart labels.

It sounds like the developers do expect the chart to be empty.  I confess that this surprises me, and I think that my expectation is more reasonable.  But that’s just one opinion.

If you want to preserve the empty-chart-by-default, maybe you could:
	- Add an “Apply” button to the page so I’d have something to press in order to load the chart data.
  or
	- Don’t provide a default Date and time range.  Change the text to say something like “Click here to select date range”.

Thanks for your help.

**Comment by DL6ER** [comment] 2019-01-22 17:37
@pi-hole/web-approvers What is your opinion on this?

I agree that there is potential for misunderstandings and that we should change something here.
Should we load today's data when opening the long-term page or should we start with empty labels?

I'd prefer the latter as
- loading today's data might already block the page for some seconds (thing of Pi Zero devices)
- today's data does no give any additional information compared to what the regular rolling 24h dashboard shows.

**Comment by Mcat12** [comment] 2019-01-22 20:05
Perhaps we could add an alert to the top of the page telling the user to choose a time range. Once they do that, remove the alert.

In the new web interface, this issue is taken care of in two ways.

1. For the query log, long term query log has been merged with the normal query log. The default time range is the last 24 hours, and it loads that from memory. To access long term date, the user changes the time range.

2. The graphics and top lists will be integrated in a similar way to the query log. The dashboard will have a time range selector, and it will default to the last 24 hours. To view long term data, the user will change the time range. See pi-hole/api#88

**Comment by DL6ER** [comment] 2019-01-22 20:06
> Perhaps we could add an alert to the top of the page telling the user to choose a time range. Once they do that, remove the alert. 

This together with an initailly empty field?

**Closed** 2019-05-18 20:08 UTC
