### ISSUE TITLE
Tooltips cut off under "forward destinations graph" [FTLDNS]

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/AdminLTE#741] opened 2018-04-30 05:03 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Tooltips should not be cut off, like how it is in the "clients" graph (FTLDNS exclusive patch)`

**Actual behaviour:**

`If tooltip is too long, it gets cut off along the sides`

**Steps to reproduce:**

`If the forward destinatiion name is too long, hover over it and you'll see it gets cut off on the left side`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`n/a`

**Troubleshooting undertaken, and/or other relevant information:**

`Nothing. I'm not familliar with the page's code`

**Comment by dschaper** [comment] 2018-04-30 05:06
Duplicate of #697 among many others. Please check the open and closed issues.

**Closed by dschaper** 2018-04-30 05:06 UTC

**Comment by dschaper** [comment] 2018-04-30 05:07
See #603 for current status.
