### ISSUE TITLE
tooltip hide client information

### ISSUE THREAD

**Issue by iacopodeenosee** [pi-hole/AdminLTE#697] opened 2018-03-16 10:15 UTC
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3
---
**Expected behaviour:**

the client chart tooltip should show me a list of the most active clients

**Actual behaviour:**

the list of clients on the graph is completely cut off as it disappears under another widget

**Steps to reproduce:**

- have many clients logged on
- open the administration page
- mouse over the customer graph

**Misc**
video -> https://youtu.be/buu_qWDVuLQ

**Solutions**

- move the height position of the tooltip to the beginning of the client graph
- show only the first 5 most active customers

**Comment by PromoFaux** [comment] 2018-03-16 10:17
>- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

And yet, Duplicate of: https://github.com/pi-hole/AdminLTE/issues/603

😉

**Closed by PromoFaux** 2018-03-16 10:17 UTC
