### ISSUE TITLE
pihole v5 web Query Log does not sort by "Reply"

### ISSUE THREAD

**Issue by bondskin** [pi-hole/AdminLTE#1249] opened 2020-05-10 06:46 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

By clicking all the columns in the Query Log the entries can be sorted
https://discourse.pi-hole.net/t/query-log-sort-by-reply-cannot-be-changed/31785

**Actual behaviour:**

It cannot be sorted by column "Reply", table remains the same

<img width="190" alt="Bildschirmfoto 2020-05-09 um 13 10 51" src="https://user-images.githubusercontent.com/55050117/81492734-80b22980-929a-11ea-8373-46232deae1a4.png">
<img width="190" alt="Bildschirmfoto 2020-05-09 um 13 10 56" src="https://user-images.githubusercontent.com/55050117/81492735-81e35680-929a-11ea-8897-0ab2bc6b02da.png">

**Steps to reproduce:**

Click on Reply, the icon will change but the sorting remains unchanged.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/rwazmz0k3j

**Troubleshooting undertaken, and/or other relevant information:**

None

**Comment by pralor** [comment] 2020-05-10 06:46
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/query-log-sort-by-reply-cannot-be-changed/31785/4

**Comment by DL6ER** [comment] 2020-05-10 07:17
The issue is caused by how the data is processed by DataTables. The displayed cell content (readable text) is different to what the API actually sends (compressed data). We'll investigate and either fix or disable sorting by the reply field in case a fix would be hurting other things. I agree that a feature that is there should also work.

**Comment by yubiuser** [comment] 2020-05-10 07:30
Maybe it can be combined with https://discourse.pi-hole.net/t/explicit-search-in-pi-hole-admin-console/28893/45

**Comment by yubiuser** [comment] 2020-12-28 05:49
Fixed by 
https://github.com/pi-hole/AdminLTE/pull/1669

**Closed** 2022-01-11 20:36 UTC
Labels: Bug
