### ISSUE TITLE
Moving Pihole/#561

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#114] opened 2016-07-08 22:01 UTC
Moving [this issue from the main Pi-Hole repo](https://github.com/pi-hole/pi-hole/issues/561)  to this one.
##

**Comment by iLlama** [comment] 2016-07-11 23:53
Having this issue again.. I have been the only one on my network browsing today though which is odd. 

I ran pihole -f and then I was able to view the query log. I guess it grew to large again.

**Comment by Mcat12** [comment] 2016-12-02 01:10
Duplicate of #130

**Closed by Mcat12** 2016-12-02 01:10 UTC
