### ISSUE TITLE
Clients (over time) should be hidden when privacy level 3 or higher is enabled. 

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/AdminLTE#932] opened 2019-04-17 15:37 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{ 1 }`

---
**Expected behaviour:**

when enabling privacy level 3 it states:         
 " Hide domains and clients: Display and store all domains as "hidden" and all clients as "0.0.0.0" This disables all tables on the dashboard "         
So one would assume since the graph isn't populated with any stats it wouldn't be shown.

more details on expected behavior:

i would think that when the privacy level has been enabled for any level higher than level 2 this graph should not be shown as there is no information shown in it.

Privacy Level 3 - 5 this graph should be off.

 **Actual behaviour:**

`{
Clients (over time) is shown as an empty graph when privacy level 3 or higher is enabled. 
}`

**Steps to reproduce:**

`{
Enable privacy level 3 and view the dashboard when logged in.
}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{
https://tricorder.pi-hole.net/v96pimhd8r!
}`

**Troubleshooting undertaken, and/or other relevant information:**

`{
Not sure how to. 
}`

**Comment by Mcat12** [comment] 2019-04-23 03:37
Have you tested enabling level 3 and waiting for a few hours? The clients in the graph would then show as `0.0.0.0` starting from the moment you changed the privacy level. Previous queries are not retroactively changed.

**Comment by mwoolweaver** [comment] 2019-04-23 06:07
will investigate. probably not a bug.

**Comment by mwoolweaver** [comment] 2019-04-23 07:42
pi-hole has been running for a couple hours and chart has yet to show any data at all.

**Comment by Mcat12** [comment] 2019-04-23 14:59
Closing the issue as there seems to be no bug.

**Comment by mwoolweaver** [comment] 2019-04-23 20:14
> The clients in the graph would then show as 0.0.0.0 starting from the moment you changed the privacy level.

this is not what's happening in my case. If you'd like I'd be willing to share a little more info via email so you can see this.

**Comment by Mcat12** [comment] 2019-04-23 21:01
It may be that the `0.0.0.0` clients are not shown in the graph. I will test this tonight. You can share info with mark@pi-hole.net if you would like.

**Comment by Mcat12** [comment] 2019-04-23 21:13
I closed this as we are correctly not showing new client information after changing the privacy level, however I see now that you are trying to get at a different point. You want to remove the graph when there is no information to be shown. That borders on a feature request (hide charts when they do not have data), but I will keep it as an issue for now, just note that it is not a bug as this is expected behavior.

**Comment by mwoolweaver** [comment] 2019-04-23 21:22
So if understand correctly.

When clients are being shown as `0.0.0.0` the Clients (over time) graph is supposed to be empty by design?

**Comment by Mcat12** [comment] 2019-04-24 00:52
Yes, you can see here that no client over time information is sent if the privacy level is 3 or higher:
https://github.com/pi-hole/FTL/blob/master/api.c#L1018

I was traveling and unable to test this until now, so sorry for any confusion.

**Comment by mwoolweaver** [comment] 2019-04-24 02:26
That's good to know! I have resorted to using uBlock to just hide it for the time being. 


So what the reason for it still being shown if it's not being populated with any data?

**Comment by Mcat12** [comment] 2019-04-24 02:31
No particular reason, that is just how it worked out when we added the privacy levels.

We are working on a new web interface to replace this one, and so we are trying to avoid any unnecessary changes to this web interface. Changes made to this interface will either need to be rewritten for the new web interface, or lost. I can change the new web interface to hide the charts based on privacy level, which is the best way to implement this feature. However, it will take time for that to happen, as actually shipping the new web interface has higher priority than this feature.

Preview: http://web.pi-hole.io/
Repo: https://github.com/pi-hole/web

**Comment by mwoolweaver** [comment] 2019-04-24 02:43
> as actually shipping the new web interface has higher priority than this feature. 

TFW I forgot this was coming . . .


Is there a way to use it with live data?

**Comment by Mcat12** [comment] 2019-04-24 02:54
There is a draft PR which has some instructions for testing the API and new web interface. Note that it is still in a alpha or even pre-alpha stage: https://github.com/pi-hole/pi-hole/pull/2692

**Comment by DL6ER** [comment] 2019-06-15 15:24
Sorry for the delay, I just discovered this issue ticket. The function @mwoolweaver asks for is already there, however, a bug prevents it from working as expected. This will be fixed by #966.

**Comment by mwoolweaver** [comment] 2019-07-16 17:59
has this fix been released yet?

**Comment by Mcat12** [comment] 2019-07-16 20:31
No, it will be released with v5.0.

**Closed** 2019-09-21 23:06 UTC
Labels: Bug, Fixed In Next Release
