### ISSUE TITLE
Info bubble floating out of the chart

### ISSUE THREAD

**Issue by maciboy** [pi-hole/AdminLTE#650] opened 2017-12-19 18:34 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn’t a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

I would like to see the complete text bubble when hovering over a graph on the dashboard.
Just the same as it is with the <Queries over last 24 hours> graph where the bubbles placed left to the cursor position.

**Actual behaviour:**

The information bubble is always below the line of the graph so most of the time its content can’t be read. Even if the graph has a high value on the y-axis there is not enough space to show the complete information bubble.
![bildschirmfoto 2017-12-19 um 19 26 41](https://user-images.githubusercontent.com/19333006/34172698-36f0487e-e4f3-11e7-8978-0da3e8515b02.png)

**Steps to reproduce:**

Go to dashboard on hover over the graph <Clients (over time)>

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`Restarted, cleared log`

**Comment by DL6ER** [comment] 2017-12-19 18:35
Duplicate of #603

**Closed by DL6ER** 2017-12-19 18:35 UTC
