### ISSUE TITLE
Adding more than 7 forward resolvers causes graph on dashboard to disappear

### ISSUE THREAD

**Issue by NEXUS2345** [pi-hole/AdminLTE#710] opened 2018-04-02 00:19 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The graph detailing the each resolvers share of the forwarded requests should be displayed along with a key with hostnames for the resolvers.

**Actual behaviour:**

The graph is not shown as it appears that the key splits into two columns and covers the graph.

**Steps to reproduce:**

Add more than 7 forward resolvers.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`ggdc32mkw8`

**Troubleshooting undertaken, and/or other relevant information:**

No troubleshooting attempted, as cause of issue seems to be quite obvious.
Screenshot of interface demonstrating issue: https://screenshots.firefox.com/dRVpjVwnQRfw0LJ2/192.168.0.178

**Comment by Mcat12** [comment] 2018-04-02 03:33
Duplicate of #635

**Closed by Mcat12** 2018-04-02 03:33 UTC
